package entities;
// Generated Aug 24, 2016 4:06:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name="countries"
    ,catalog="wladekjsf"
)
public class Countries  implements java.io.Serializable {


     private int id;
     private String name;
     private String capitalCity;
     private Long poopulation;

    public Countries() {
    }

	
    public Countries(int id) {
        this.id = id;
    }
    public Countries(int id, String name, String capitalCity, Long poopulation) {
       this.id = id;
       this.name = name;
       this.capitalCity = capitalCity;
       this.poopulation = poopulation;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="capital_city", length=150)
    public String getCapitalCity() {
        return this.capitalCity;
    }
    
    public void setCapitalCity(String capitalCity) {
        this.capitalCity = capitalCity;
    }

    
    @Column(name="poopulation")
    public Long getPoopulation() {
        return this.poopulation;
    }
    
    public void setPoopulation(Long poopulation) {
        this.poopulation = poopulation;
    }




}


